version: "3.9"
services:
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=celery_tasks

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/pgdata/
      - POSTGRES_DB=ithilleldb
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432

  web:
    build: .
    image: jul7-dango
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/src
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    ports:
      - 8000:8000

  celery:
    build: .
    image: jul7-dango
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/src
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    command: "celery -A config.celery.app worker"

volumes:
  pgdata: {}